#!/usr/bin/env node

const program = require('commander')
const pkg = require('../package.json')

program._name = 'cli/dkt'
program
  .version(pkg.version)
  .command('service [command]', 'deploy services')
  .command('stepfunctions [command]', 'deploy, start step functions')
  .command('test [command]', 'run tests')
  .parse(process.argv)
