#!/usr/bin/env node

const program = require('commander')

program._name = 'cli/dkt stack'
program
  .command('build', 'build the application stack')
  .command('deploy', 'build and deploy application stack')
  .parse(process.argv)
