#!/usr/bin/env node

const program = require('commander')

program
  .command('deploy', 'deploy Lambda functions')
  .command('build', 'build lambda functions')
  .command('bundle', 'bundle lambda functions')
  .parse(process.argv)
